# Generated by Django 2.2.26 on 2022-06-28 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'ADMIN'), (2, 'CUSTOMER'), (3, 'DRIVER')], default=2, verbose_name='user_type'),
        ),
    ]
