# Generated by Django 2.2.28 on 2022-07-02 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220630_0403'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Full name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('date_of_birth', models.DateField(verbose_name='Date of birth')),
                ('phone', models.CharField(max_length=100, verbose_name=' Phone')),
                ('gender', models.IntegerField(choices=[(1, 'Male'), (2, 'Female')], default=2, verbose_name='Gender')),
                ('address', models.TextField(verbose_name='Address')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('zip_code', models.CharField(max_length=100, verbose_name='Zip code')),
                ('state', models.CharField(max_length=100, verbose_name='State')),
                ('document_front_photo', models.ImageField(upload_to=users.utils.file_upload)),
                ('document_back_photo', models.ImageField(upload_to=users.utils.file_upload)),
                ('face_photo', models.ImageField(upload_to=users.utils.file_upload)),
                ('profile_image', models.ImageField(upload_to=users.utils.file_upload)),
                ('is_verify', models.BooleanField(default=False)),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Customer Profile',
                'verbose_name_plural': "Customer's Profile",
                'ordering': ['-id'],
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_verified_by_admin',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
