# Generated by Django 2.2.28 on 2022-07-10 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20220704_2341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerprofile',
            old_name='is_verify',
            new_name='is_approved',
        ),
        migrations.RenameField(
            model_name='driverprofile',
            old_name='is_verify',
            new_name='is_approved',
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='address_photo',
            field=models.ImageField(blank=True, null=True, upload_to=users.utils.file_upload, validators=[users.utils.file_validation]),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='identity_document_back_photo',
            field=models.ImageField(blank=True, null=True, upload_to=users.utils.file_upload, validators=[users.utils.file_validation]),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='identity_document_front_photo',
            field=models.ImageField(blank=True, null=True, upload_to=users.utils.file_upload, validators=[users.utils.file_validation]),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='license_back_photo',
            field=models.ImageField(blank=True, null=True, upload_to=users.utils.file_upload, validators=[users.utils.file_validation]),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='license_front_photo',
            field=models.ImageField(blank=True, null=True, upload_to=users.utils.file_upload, validators=[users.utils.file_validation]),
        ),
        migrations.CreateModel(
            name='VehicleInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255, verbose_name='Model name')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('license_plate_nubmer', models.CharField(max_length=255, verbose_name='License plate number')),
                ('driver_license_number', models.CharField(max_length=255, verbose_name='Driving license number')),
                ('license_issued_in', models.CharField(max_length=100, verbose_name='License issued in')),
                ('mvr_document', models.FileField(upload_to=users.utils.file_upload, validators=[users.utils.file_validation])),
                ('insurance_document', models.FileField(upload_to=users.utils.file_upload, validators=[users.utils.file_validation])),
                ('operating_card_document', models.FileField(upload_to=users.utils.file_upload, validators=[users.utils.file_validation])),
                ('inspection_document', models.FileField(upload_to=users.utils.file_upload, validators=[users.utils.file_validation])),
                ('image', models.ImageField(upload_to=users.utils.file_upload, validators=[users.utils.file_validation])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_info', to='users.DriverProfile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vehicle Info',
                'verbose_name_plural': 'Vehicle Infos',
                'ordering': ['-id'],
            },
        ),
    ]
