# Generated by Django 2.2.28 on 2022-07-23 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20220713_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='document_back_photo',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='document_front_photo',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='face_photo',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='profile_image',
        ),
        migrations.CreateModel(
            name='CustomerDocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_front_photo', models.ImageField(upload_to=users.utils.file_upload, validators=[users.utils.file_validation])),
                ('document_back_photo', models.ImageField(upload_to=users.utils.file_upload, validators=[users.utils.file_validation])),
                ('face_photo', models.ImageField(upload_to=users.utils.file_upload, validators=[users.utils.file_validation])),
                ('profile_image', models.ImageField(upload_to=users.utils.file_upload, validators=[users.utils.file_validation])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_document', to='users.CustomerProfile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_document', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer Document',
                'verbose_name_plural': 'Customer Documents',
                'ordering': ['-id'],
            },
        ),
    ]
