# Generated by Django 2.2.28 on 2022-07-26 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20220723_2312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverprofile',
            name='address_photo',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='identity_document_back_photo',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='identity_document_front_photo',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='license_back_photo',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='license_front_photo',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='tax_no',
            field=models.CharField(max_length=100, null=True, verbose_name='Tax number'),
        ),
        migrations.AlterField(
            model_name='customerdocuments',
            name='document_back_photo',
            field=models.ImageField(null=True, upload_to=users.utils.file_upload, validators=[users.utils.file_validation]),
        ),
        migrations.AlterField(
            model_name='customerdocuments',
            name='document_front_photo',
            field=models.ImageField(null=True, upload_to=users.utils.file_upload, validators=[users.utils.file_validation]),
        ),
        migrations.AlterField(
            model_name='customerdocuments',
            name='face_photo',
            field=models.ImageField(null=True, upload_to=users.utils.file_upload, validators=[users.utils.file_validation]),
        ),
        migrations.AlterField(
            model_name='customerdocuments',
            name='profile_image',
            field=models.ImageField(null=True, upload_to=users.utils.file_upload, validators=[users.utils.file_validation]),
        ),
        migrations.AlterField(
            model_name='customerdocuments',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_document', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Availability',
        ),
    ]
