# Generated by Django 2.2.28 on 2022-07-26 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0009_auto_20220726_2222'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default=None, max_length=25, null=True)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_at', models.DateTimeField(null=True)),
                ('total_hours', models.CharField(max_length=50)),
                ('total_price', models.DecimalField(decimal_places=3, default=None, max_digits=7, null=True)),
                ('pick_up_location', models.CharField(max_length=255)),
                ('pick_up_latitude', models.CharField(max_length=50)),
                ('pick_up_longitude', models.CharField(max_length=50)),
                ('drop_off_location', models.CharField(max_length=255)),
                ('drop_off_longitude', models.CharField(max_length=50)),
                ('drop_off_latitude', models.CharField(max_length=50)),
                ('is_accepted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_request_customer', to='users.CustomerProfile')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_request_driver', to='users.DriverProfile')),
            ],
        ),
    ]
