# Generated by Django 2.2.28 on 2022-07-27 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20220726_2222'),
        ('schedule_ride', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScheduleRequest',
            new_name='ScheduleRide',
        ),
    ]
