# Generated by Django 2.2.28 on 2022-07-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_ride', '0002_auto_20220727_1320'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduleride',
            options={'ordering': ['-id'], 'verbose_name': 'Schedule Ride', 'verbose_name_plural': 'Schedule Rides'},
        ),
        migrations.RenameField(
            model_name='scheduleride',
            old_name='is_accepted',
            new_name='is_canceled',
        ),
        migrations.AddField(
            model_name='scheduleride',
            name='canceled_by',
            field=models.CharField(choices=[(1, 'ADMIN'), (2, 'CUSTOMER'), (3, 'DRIVER')], max_length=100, null=True),
        ),
    ]
