# Generated by Django 2.2.28 on 2022-07-18 12:21

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=256)),
                ('name', models.EmailField(max_length=256)),
                ('email', models.EmailField(max_length=256)),
                ('phone', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('user_type', models.IntegerField()),
                ('currency', models.CharField(default='', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_customer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ('user__username', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='CustomerPaymentSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(max_length=255, unique=True, verbose_name='Source ID')),
                ('is_default', models.BooleanField(default=False, verbose_name='Default')),
                ('details', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('fingerprint', models.CharField(blank=True, max_length=120, null=True, verbose_name='Fingerprint')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_source', to='stripe_app.StripeCustomer')),
            ],
            options={
                'verbose_name': 'Customer Payment Source',
                'verbose_name_plural': 'Customer Payment Sources',
                'ordering': ('-created_at',),
            },
        ),
    ]
