# Generated by Django 2.2.28 on 2022-07-20 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20220713_1849'),
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracking',
            old_name='latitude',
            new_name='driver_latitude',
        ),
        migrations.RenameField(
            model_name='tracking',
            old_name='longitude',
            new_name='driver_longitude',
        ),
        migrations.AddField(
            model_name='tracking',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255, null=True)),
                ('is_accepted', models.BooleanField(default=False)),
                ('longitude', models.CharField(max_length=50)),
                ('latitude', models.CharField(max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_customer', to='users.CustomerProfile')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_driver', to='users.DriverProfile')),
            ],
        ),
    ]
