# Generated by Django 2.2.28 on 2022-07-20 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_auto_20220720_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='driver_latitude',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='driver_longitude',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
