# Generated by Django 2.2.28 on 2022-07-20 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_auto_20220720_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking',
            name='ended_by',
            field=models.CharField(choices=[(1, 'ADMIN'), (2, 'CUSTOMER'), (3, 'DRIVER')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tracking',
            name='request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tracking.Request'),
        ),
        migrations.AddField(
            model_name='tracking',
            name='total_distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
